server:
  port: 8080

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: orders

redis:
  host: redis
  port: 6379
  password: redis
  db: 0
  ttl: 1m

kafka:
  broker: "kafka:9092"
  topic: "order_created"
  group_id: "orders-service-group"

logger:
  level: info
  output: stdout
