server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: orders

kafka:
  broker: "localhost:9092"
  topic: "order_created"
  group_id: "orders-service-group"

logger:
  level: info         # debug, info, warn, error
  output: stdout      # stdout, stderr или путь к файлу